//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSACH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Компьютерный_магазинEntities : DbContext
    {
        public static Компьютерный_магазинEntities _context;
        public Компьютерный_магазинEntities()
            : base("name=Компьютерный_магазинEntities")
        {
        }

        public static Компьютерный_магазинEntities GetContext()
        {
            if (_context == null)
                _context = new Компьютерный_магазинEntities();

            return _context;
        }

        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<The_Supplier> The_Supplier { get; set; }
    }
}
